# Generated by Django 6.0.6 on 2026-07-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_userrequest_check_valid_request_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='project_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='target',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
