# Generated by Django 6.0.6 on 2026-07-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_userrequest_project_id_alter_userrequest_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='requested_files',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
