# Generated by Django 6.0.2 on 2026-03-28 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New project', max_length=100)),
                ('description', models.CharField(default='Project description', max_length=5000)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='new domain', max_length=100)),
            ],
            options={
                'db_table': 'project_domains',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='New task', max_length=100)),
                ('description', models.CharField(blank=True, default='Describe the task..', max_length=300)),
                ('start_date', models.DateField(default='1000-10-10')),
                ('end_date', models.DateField(default='3000-10-10')),
            ],
            options={
                'db_table': 'projects_tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTaskParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'project_task_participations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='new role', max_length=50)),
                ('can_accept_invites', models.BooleanField(default=False)),
                ('can_invite_others', models.BooleanField(default=False)),
                ('can_kick_others', models.BooleanField(default=False)),
                ('can_change_roles', models.BooleanField(default=False)),
                ('can_start_calls', models.BooleanField(default=False)),
                ('can_add_tasks', models.BooleanField(default=False)),
                ('can_delete_tasks', models.BooleanField(default=False)),
                ('can_modify_tasks', models.BooleanField(default=False)),
                ('can_change_project_settings', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'db_table': 'project_roles',
            },
        ),
        migrations.CreateModel(
            name='UserProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('role', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='projects.projectrole')),
                ('user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_project_roles',
            },
        ),
    ]
