# Generated by Django 6.0.6 on 2026-07-28 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_projectrole_can_modify_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to='projects.project'),
        ),
    ]
