# Generated by Django 6.0.2 on 2026-02-26 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('login_date', models.DateTimeField(default=datetime.datetime(2026, 2, 26, 16, 48, 20, 311186))),
                ('birthday', models.DateField()),
                ('email', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
